import 'package:flutter/material.dart';

const kMainColor = Color(0xFF4EAE89);
const kLogoImage = 'assets/images/logo.png';

const kName = 'name';
const kId = 'id';
const kAddress = 'address';
const kEmail = 'email';
const kPhoneNumber = 'phoneNumber';
const kCategory = 'category';
const kImageUrl = 'imageUrl';
const kPrice = 'price';
const kLiked = 'liked';
const kDescription = 'description';
const kQuantity = 'quantity';
const kMealName = 'strMeal';
const kMealId = 'idMeal';
const kMealIngredientName = 'strIngredient';
const kMealIngredientMeasure = 'strMeasure';
const kMealImageUrl = 'strMealThumb';
const kMealVideoUrl = 'strYoutube';
const kMealRecipe = 'strInstructions';
const kMealArea = 'strArea';
const kMealCategory = 'strCategory';
const kMealIngredientsList = 'ingredients';
const kTitle = 'title';
const kServings = 'servings';
const kInngredients = 'ingredients';
const kInstructions = 'instructions';
const kNutrentAmount = 'amount';
const kNutrentUnit = 'unit';
const kNutrentPercent = 'percentOfDailyNeeds';
const kSpoonAcularApiKey = '16b0bd59b36a41ab8ee6762f01eabb41';
